
--PRICE data
INSERT INTO PRICE(ID, AMOUNT) VALUES ('RENT_PER_DAY', 2.0);
INSERT INTO PRICE(ID, AMOUNT) VALUES ('FEE_PER_DAY', 3.0);

--VHS data
INSERT INTO VHS(TITLE, PUBLISHER, YEAR, AVAILABLE) VALUES ('The Lion King', 'Disney', 1994, TRUE);
INSERT INTO VHS(TITLE, PUBLISHER, YEAR, AVAILABLE) VALUES ('The Lion King', 'Disney', 1994, TRUE);
INSERT INTO VHS(TITLE, PUBLISHER, YEAR, AVAILABLE) VALUES ('Titanic', 'Paramount Pictures', 1997, TRUE);
INSERT INTO VHS(TITLE, PUBLISHER, YEAR, AVAILABLE) VALUES ('Jurassic Park', 'Universal Studios', 1993, TRUE);

--User data
INSERT INTO APP_USER(NAME, SURNAME, USERNAME, EMAIL) VALUES ('John', 'Doe', 'jdoe', 'jdoe@gmail.com');
INSERT INTO APP_USER(NAME, SURNAME, USERNAME, EMAIL) VALUES ('Ned', 'Harret', 'nharret', 'nharret@gmail.com');
INSERT INTO APP_USER(NAME, SURNAME, USERNAME, EMAIL) VALUES ('Darell', 'Feron', 'dferon', 'dferon@gmail.com');
INSERT INTO APP_USER(NAME, SURNAME, USERNAME, EMAIL) VALUES ('Ana', 'Wilcher', 'awilcher', 'awilcher@gmail.com');

