
--PRICE data
INSERT INTO PRICE(ID, AMOUNT) VALUES ('RENT_PER_DAY', 2.0);
INSERT INTO PRICE(ID, AMOUNT) VALUES ('FEE_PER_DAY', 0.5);

--VHS data
INSERT INTO VHS(TITLE, PUBLISHER, YEAR) VALUES ('The Lion King', 'Disney', 1994);
INSERT INTO VHS(TITLE, PUBLISHER, YEAR) VALUES ('The Lion King', 'Disney', 1994);
INSERT INTO VHS(TITLE, PUBLISHER, YEAR) VALUES ('Titanic', 'Paramount Pictures', 1997);
INSERT INTO VHS(TITLE, PUBLISHER, YEAR) VALUES ('Jurassic Park', 'Universal Studios', 1993);